# Rules

.only-master-and-production:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "production"'
      changes:
        - "${PACKAGE_PATH}/**/*"
    - when: never

.only-production:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "production"'
      changes:
        - "${PACKAGE_PATH}/**/*"
    - when: never

.only-master:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      changes:
        - "${PACKAGE_PATH}/**/*"
    - when: never

.only-merge-request:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME != "master" && $CI_COMMIT_REF_NAME != "production"'
      changes:
        - "${PACKAGE_PATH}/**/*"
    - when: never
